services:
  - type: web
    name: pm25-tashkent-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r service1/requirements.txt
    startCommand: uvicorn service2_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true
